# Generated by Django 5.0.14 on 2025-10-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='can_delete',
            field=models.BooleanField(default=False, help_text='Use in jupyter notebooks'),
        ),
    ]
