# Generated by Django 5.0.14 on 2025-10-25 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('product', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='embedding',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='embedding',
            name='object_id',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
